#  spring2.x 以上，移除自动配置类 来代替 security.basic.enable=false
#  @SpringBootApplication(exclude = {SecurityAutoConfiguration.class})
#  或者配置
#  HttpSecurity http
#  http.authorizeRequests().antMatchers("/**").permitAll();

spring:
  profiles:
    active: dev
  security:
#    user:
#      password: 123
#  #    - "/v2/api-docs"
#
#      name: 123
#








---

spring:
  profiles: test
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false